import { type ClassValue, clsx } from "clsx";
import { extendTailwindMerge } from "tailwind-merge";

const customTwMerge = extendTailwindMerge({
  extend: {
    classGroups: {
      "font-size": [
        {
          text: [
            "display-lg",
            "headline-md",
            "headline-sm",
            "body-lg",
            "body-md",
            "body-sm",
            "label-caps",
            "label-code-md",
            "label-code-sm",
          ],
        },
      ],
      "text-color": [
        {
          text: [
            "primary",
            "primary-container",
            "primary-fixed",
            "primary-fixed-dim",
            "on-primary",
            "on-primary-container",
            "on-primary-fixed",
            "on-primary-fixed-variant",
            "secondary",
            "secondary-container",
            "secondary-fixed",
            "secondary-fixed-dim",
            "on-secondary",
            "on-secondary-container",
            "on-secondary-fixed",
            "on-secondary-fixed-variant",
            "tertiary",
            "tertiary-container",
            "tertiary-fixed",
            "tertiary-fixed-dim",
            "on-tertiary",
            "on-tertiary-container",
            "on-tertiary-fixed",
            "on-tertiary-fixed-variant",
            "background",
            "on-background",
            "surface",
            "surface-dim",
            "surface-bright",
            "surface-variant",
            "surface-container-lowest",
            "surface-container-low",
            "surface-container",
            "surface-container-high",
            "surface-container-highest",
            "on-surface",
            "on-surface-variant",
            "outline",
            "outline-variant",
            "inverse-surface",
            "inverse-on-surface",
            "inverse-primary",
            "error",
            "error-container",
            "on-error",
            "on-error-container",
          ],
        },
      ],
      "bg-color": [
        {
          bg: [
            "primary",
            "primary-container",
            "primary-fixed",
            "primary-fixed-dim",
            "on-primary",
            "on-primary-container",
            "on-primary-fixed",
            "on-primary-fixed-variant",
            "secondary",
            "secondary-container",
            "secondary-fixed",
            "secondary-fixed-dim",
            "on-secondary",
            "on-secondary-container",
            "on-secondary-fixed",
            "on-secondary-fixed-variant",
            "tertiary",
            "tertiary-container",
            "tertiary-fixed",
            "tertiary-fixed-dim",
            "on-tertiary",
            "on-tertiary-container",
            "on-tertiary-fixed",
            "on-tertiary-fixed-variant",
            "background",
            "surface",
            "surface-dim",
            "surface-bright",
            "surface-variant",
            "surface-container-lowest",
            "surface-container-low",
            "surface-container",
            "surface-container-high",
            "surface-container-highest",
            "on-background",
            "on-surface",
            "on-surface-variant",
            "outline",
            "outline-variant",
            "inverse-surface",
            "inverse-on-surface",
            "inverse-primary",
            "error",
            "error-container",
            "on-error",
            "on-error-container",
          ],
        },
      ],
      "border-color": [
        {
          border: [
            "primary",
            "primary-container",
            "primary-fixed",
            "primary-fixed-dim",
            "on-primary",
            "on-primary-container",
            "on-primary-fixed",
            "on-primary-fixed-variant",
            "secondary",
            "secondary-container",
            "secondary-fixed",
            "secondary-fixed-dim",
            "on-secondary",
            "on-secondary-container",
            "on-secondary-fixed",
            "on-secondary-fixed-variant",
            "tertiary",
            "tertiary-container",
            "tertiary-fixed",
            "tertiary-fixed-dim",
            "on-tertiary",
            "on-tertiary-container",
            "on-tertiary-fixed",
            "on-tertiary-fixed-variant",
            "background",
            "surface",
            "surface-dim",
            "surface-bright",
            "surface-variant",
            "surface-container-lowest",
            "surface-container-low",
            "surface-container",
            "surface-container-high",
            "surface-container-highest",
            "on-background",
            "on-surface",
            "on-surface-variant",
            "outline",
            "outline-variant",
            "inverse-surface",
            "inverse-on-surface",
            "inverse-primary",
            "error",
            "error-container",
            "on-error",
            "on-error-container",
          ],
        },
      ],
    },
  },
});

/**
 * Combines multiple className strings or objects and resolves Tailwind class conflicts.
 * Augmented with ClubOS design system custom font-size and color tokens to ensure
 * text color and typography utility classes never collide or drop each other.
 */
export function cn(...inputs: ClassValue[]): string {
  return customTwMerge(clsx(inputs));
}
